function createfigure2(cdata1, cdata2, newmap, outputpdfname)
%CREATEFIGURE(cdata1, cdata2)
%  CDATA1:  image cdata
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 03-Sep-2023 12:49:05

% Create figure
figure1 = figure('PaperOrientation','landscape',...
    'PaperSize',[29.69999902 20.99999864],'Colormap',newmap,'Color',[1 1 1]);

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Create ylabel
ylabel('variance of fecundity selection coefficient','FontSize',11);

% Create xlabel
xlabel('fecundity selection coefficient','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0.5 5.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot1,[0.5 5.5]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot1,[-1 1]);
box(subplot1,'on');
axis(subplot1,'square');
axis(subplot1,'ij');
hold(subplot1,'off');
% Set the remaining axes properties
% set(subplot1,'CLim',[min([cdata1(:);cdata2(:)]) max([cdata1(:);cdata2(:)])],'Layer','top',...
%     'XTick',[1:5],'XTickLabel',{'0.2','0.4','0.6','0.8','0.95'},'YTick',...
%     [1:5],'YTickLabel',{'0.45','0.35','0.25','0.15','0.05'});

set(subplot1,'CLim',[-0.226688700681677 1],'Layer','top',...
    'XTick',[1:5],'XTickLabel',{'0.2','0.4','0.6','0.8','0.95'},'YTick',...
    [1:5],'YTickLabel',{'0.45','0.35','0.25','0.15','0.05'});

% Create colorbar
colorbar(subplot1);

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create image
image(cdata2,'Parent',subplot2,'CDataMapping','scaled');

% Create ylabel
ylabel('variance of fecundity selection coefficient','FontSize',11);

% Create xlabel
xlabel('fecundity selection coefficient','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0.5 5.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot2,[0.5 5.5]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot2,[-1 1]);
box(subplot2,'on');
axis(subplot2,'square');
axis(subplot2,'ij');
hold(subplot2,'off');
% Set the remaining axes properties
% set(subplot2,'CLim',[min([cdata1(:);cdata2(:)]) max([cdata1(:);cdata2(:)])],'Layer','top',...
%     'XTick',[1:5],'XTickLabel',{'0.2','0.4','0.6','0.8','0.95'},'YTick',...
%     [1:5],'YTickLabel',{'0.45','0.35','0.25','0.15','0.05'});
set(subplot2,'CLim',[-0.226688700681677 1],'Layer','top',...
    'XTick',[1:5],'XTickLabel',{'0.2','0.4','0.6','0.8','0.95'},'YTick',...
    [1:5],'YTickLabel',{'0.45','0.35','0.25','0.15','0.05'});

% Create colorbar
colorbar(subplot2);

saveas(gcf,outputpdfname)